#!/bin/sh
#
# afd:       Starts the AFD
#
# chkconfig: 235 70 10
# description: AFD is an automatic file distributor. It is used to \
#              distribute data files via FTP, FTPS, SMTP and/or SCP.
### BEGIN INIT INFO
# Required-Start: $local_fs $network
# Required-Stop: $local_fs $network
# Default-Start: 2 3 5
# Default-Stop: 0 1 6
# Short-Description: Starts the AFD
# Description: AFD is an automatic file distributor. It is used to
#              distribute data files via FTP, FTPS, SMTP and/or SCP.
### END INIT INFO


if [ -r /etc/sysconfig/afd ]
then
    AFD_USERS="`grep \^AFD_USER_ /etc/sysconfig/afd | cut -d '=' -f2`"
else
    AFD_USERS=""
fi
if [ "$AFD_USERS" = "" ]
then
   exit 0
fi


# See how we were called.
case "$1" in
  start)
	RETVAL=1
	for afduser in $AFD_USERS
	do
	   echo -n "Starting AFD for $afduser : "
	   su - $afduser -c "afd -a"
	   TMPVAL=$?
	   if [ $TMPVAL -eq 0 ]
	   then
	      RETVAL=0
	   fi
	done
	echo
	[ $RETVAL -eq 0 ] && touch /var/lock/subsys/afd
	;;
  stop)
	RETVAL=1
	for afduser in $AFD_USERS
	do
	   echo -n "Stopping AFD for $afduser : "
	   su - $afduser -c "afd -S"
	   TMPVAL=$?
	   if [ $TMPVAL -eq 0 ]
	   then
	      RETVAL=0
	   fi
	done
	echo
	[ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/afd
	;;
  restart)
	$0 stop
	sleep 2
	$0 start
	RETVAL=$?
	;;
  condrestart)
	if [ -f /var/lock/subsys/afd ]
	then
	   $0 restart
	else
	   RETVAL=0
	fi
	;;
  status)
	NOT_RUNNING=""
	for afduser in $AFD_USERS
	do
	   su - $afduser -c "afd -c"
	   RETVAL=$?
	   if [ $RETVAL -ne 5 ]
	   then
	      NOT_RUNNING="`echo $NOT_RUNNING` $afduser"
	   fi
	done
	if [ "$NOT_RUNNING" = "" ]
	then
	   echo "AFD for $AFD_USERS is running."
	   RETVAL=0
	else
	   echo "AFD for $NOT_RUNNING is NOT active."
	   RETVAL=1
	fi
	;;
  *)
	echo "*** Usage: afd {start|stop|restart|condrestart|status}"
	RETVAL=1
	;;
esac

exit $RETVAL
