#!/bin/sh
#
# Description   : This script allows you to login from a remote host.
#                 Your hostname must be entered in the local .rhost
#                 file.
#                 NOTE: You must adapt AFD_WORK_DIR to your environment.
#
# Synopsis      : rmon_ctrl <local hostname>
#
# Author        : H.Kiehl
# Date          : 02.01.1999
# Modifications : 17.05.2004 H.Kiehl Allow to parse parameters.
#

AFD_WORK_DIR="/home/afd"
PATH=$PATH:/usr/bin
DISPLAY=$1:0.0
export DISPLAY AFD_WORK_DIR

shift

mon_ctrl $*
